### ISSUE TITLE
Recent regressions - anybody else see them?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10169]
Some of my recently merged PR's seem faulty.

- [x] #10117 - on one of my boxes, the Mint 21.2 Cinnamon one, I get a completely derailed Window Manager. Entire screen blinking, or dragging the right edge resizes the left edge or such nonsense. Might be correlated with starting from Studio. Anybody else? Or anybody running just fine on Cinnamon?
- [x] #8962 - city overview header icons should stay put when scrolling the cities, and I get jumps to the left on first click. I think I mentioned that in the #10157 comment.. Repeat to reach more people. Hearing from people having header click work fine on the latest code would also be valuable, but I'm pretty sure that is not random and immediately debuggable.
- [x] #10154 - I've seen the menu+civ / overview buttons moved down despite there being enough room, possibly only after resizing the window. Anybody seen when exactly this happens?
