### ISSUE TITLE
LibGdx 1.12.1 update TO-DO

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10440]
Little brainstorm:

- [x] Read their changelog - [short](https://libgdx.com/news/2023/11/gdx-1-12-1) and [long](https://github.com/libgdx/libgdx/blob/master/CHANGES)
- [x] Check HardenGdxAudio - despite their 6973 PR our noDevice and update and access to the music array are still fine. But if it turns out noDevice remaining static after the constructor even when devices change is a mistake on their part, then we'd have to adapt.
- [ ] Check Desktop window size persistence
- [x] Check getReadonlyPixmap - yup upstream unchanged
- [x] Check ColorMarkupLabel prefWidth - yup hack still necessary
- [x] Check DesktopScreenMode.setWindowedMode writeback to config - no relevant change to the function
- [ ] Check for changes to scrollfocus or keyboard focus handling
- [x] I know my hacks to educate SelectBox were not necessary enough and thus not merged, so no trouble on that front. Just one of their post-1.10 fixes I remember reflecting around to truly replace the dropdown's SelectBox.SelectBoxScrollPane.List with something more flexible.
- [x] See if StageMouseOverDebug's use of hit can be made to *not* validate WidgetGroups (Gdx 1.12.0 breaking change) - BS. validate would occur on the next frame anyway.

Ye whoso knoweth what mysteries dwell here I implore thee to append thy dual nickels...
