### ISSUE TITLE
Units can sometimes stand on illegal tiles, possibly crashing the game when selected

### ISSUE THREAD

**Issue by avdstaaij** [yairm210/Unciv#4237]
This issue is intended to gather the occurances of the bug described by the title, and to have a single issue I can link to when another case is reported. I'll edit/close/re-open this issue as new cases are solved or discovered.

### The issue

In various cases, units are able to stand on a tile they aren't actually able to move to. Selecting such a unit crashes the game if they can reach a tile with a friendly unit of the same type (military / civilian) that can also reach them. For the reason why this happens, see https://github.com/yairm210/Unciv/pull/4049#issuecomment-858201026.

### Cases

- [x] ~**1.** Accepting a trade in which you sell a city to a civ whose tiles you can't enter at the start of your turn while you still have units inside its borders.~ Fixed in #4161.
- [x] ~**2.** #4231: Liberating a city with an enemy civilian unit in it; the civilian unit will be captured and will remain in the liberated city.~ Fixed in #4239.
- [x] ~**3.** If a coastal city with a naval unit in it is razed to the ground, the naval unit remains on the tile where the city center was (reported in Discord). Save file: [The_Ottomans_-_Destroyer_on_land_bug.txt](https://github.com/yairm210/Unciv/files/6697854/The_Ottomans_-_Destroyer_on_land_bug.txt).~ Fixed in #4238.
- [x] ~**4.** Capturing a civilian unit in water before researching optics (reported in Discord).~ Fixed in #4701

**Comment by yairm210** [comment]
All fixed :)

**Comment by avdstaaij** [comment]
Someone on Discord found another case (number 4), which I'll solve when I have time.
@yairm210, could you re-open this? I can't because you are the one who closed it. :/
