### ISSUE TITLE
Personal ToDo-list

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#4279]
This issue will contain the features I'm planning to implement in the near or less near future. It is meant as a personal todolist, as well as being a list of potential upcoming features for interested users. As such, the issue will be closed immediately, as to avoid clutterring up the list of open issues. It is not meant for suggesting things I work on, if you want something to be implemented, put it in #suggestions on discord, create a sperate issue or add it to #663. I read these regularly, and if I deem your suggestion interesting enough, I might add it to this list. Feature requests in this thread will be ignored. If you want to discuss whether or how something should be implemented, feel free to respond. The issues in this list are not ordered within each category, I work on what I feel is fun to work on :)

In Progress:
- [] Implement great admirals - #4265
- [] Fix bugs I implemented

Short term plans:
- [] Check and fix all promotions
- [] Science button shows progress for current tech
- [] Privateer
- [] Netherlands
- [] City State gold gifts
- [] CN Tower gives free broadcast towers in all the cities of the owner of the CN tower

Long term plans:
- [] Generalize Uniques
- [] Border growth in cities
- [] Embarked units are different from military and civilian units
- [] Religion
- [] Generalize more Uniques
- [] Huns
- [] City State unit gift (?)
- [] Diplomatic Victory
- [] Spaceship parts are units
- [] Generalize even more uniques
- [] Espionage (?)
- [] Extract constants to JSON file for more moddability(?)
-  [] Go through the entire codebase to find all uniques and translatable strings, and add these to the wiki / translation file (?)
