### ISSUE TITLE
Implementation of Religion - Roadmap

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#4290]
This issue is meant as a collection of features that religion should include once implemented. I have started working on this very large new feature, and am planning to gradually implement more parts of it over the following weeks/months. While waiting for previous PR to be merged, I'll make smaller updates for other features in the meantime. The issues below are in the approximate order at which I'll start implementing them and includes features already implemented.

Roadmap:
- [x] Button for the user to access this HIGHLY EXPERIMENTAL feature - #4291
- [x] Shrines, a civReligionManager for civs - #4291
- [x] Pantheons, a cityRelgionManager for cities (basic implementation, only a single religion per city) - #4296 
- [x] Great Prophets, used for spreading religion to different cities (immediately replaces previous religion), can be earned with faith - #4356 
- [x] Great Prophet can create religions - #4505 
- [x] Follower beliefs - #4530
- [x] Founder beliefs
- [x] A UI for viewing the beliefs you and other players have chosen
- [x] Purchase missionaries with faith (groundwork for buying other units also) - #4568
- [x] Cities can have multiple different religions competing inside
- [x] Religion spreads to nearby cities with trade routes or something, I have yet to read up on how exactly this works
- [x] A UI for viewing the religions inside cities
- [x] Inquisitors
- [x] Great Prophets can reform religions with Enhancer and extra Follower believes
- [x] Great prophets may be used before founding a pantheon to also choose a pantheon belief
- [x] AI will found & enhance religions (randomly chosen beliefs for now)
- [x] Buy Great People with faith when completing certain policy trees
- [x] Somewhere add to a UI what cities are holy cities
- [x] Starting from the industrial era, lots of things change (no more great prophet generation, etc.)
- [x] Upon founding a religion, change all existing great prophets to be of that religion
- [x] May choose a different name for your religion
- [x] Spreading religion with a great prophet also removes other religions somewhat or something
- [x] Renaming a religion changes notifications
- [x] Religious city-states
- [x] Sharing a religion with a city-state decreases rate of influence decrease or something
- [x] Religious wonders (Taj Mahal, Grand Temple, etc.)
- [x] AI improvement so that they will choose beliefs that are directly benefiting them
- [x] AI improvement so they can actually buy and use religious units
- [x] AI buys religious buildings
- [ ] AI for buying great persons with Faith
- [x] AI chooses when to spend faith and when to save up
- [x] AI for great prophets when they don't have a religion
- [X] AI uses inquisiteurs to remove religions
- [x] Temple replacements should become faith buildings instead of culture buildings
- [x] Holy Warriors belief
- [x] Civs should have a favoured religion
- [x] Piety policy tree
- [x] Update existing wonders that had their stats changed (Stonehenge producing faith, etc.)
- [x] Indication that religion is disabled when it is
- [ ] Inquisitors should be able to permanently remove religious pressure from holy cities ([wiki](https://civilization.fandom.com/wiki/Holy_City_(Civ5)))

**Comment by logicminimal** [comment]
one thing i will suggest: for god sake make missionaires different from great merchants and not make them great persons

**Comment by logicminimal** [comment]
one with the nature pantheon should provide double yields for spain as well, dont know if implemented

**Comment by xlenstra** [comment]
> one with the nature pantheon should provide double yields for spain as well, dont know if implemented

Feel free to test it out, if it isn't, tell me and I'll fix it

**Comment by logicminimal** [comment]
> > one with the nature pantheon should provide double yields for spain as well, dont know if implemented
> 
> Feel free to test it out, if it isn't, tell me and I'll fix it

yep it still provides 4 faith with spain, would send a screenshot but something is wrong with GitHub

**Comment by xlenstra** [comment]
> one thing i will suggest: for god sake make missionaires different from great merchants and not make them great persons

It's been 2 months and I still have no idea what you meant by this, mind explaining?

**Comment by logicminimal** [comment]
> > one thing i will suggest: for god sake make missionaires different from great merchants and not make them great persons
> 
> It's been 2 months and I still have no idea what you meant by this, mind explaining?

the missionaires in the religion mod were implemented as reskinned great merchants

**Comment by logicminimal** [comment]
since religion is most probably going to be enabled for all games in the future just like in civ5, will the stats be implemented after religion is good enough to be included within every game?

**Comment by whatsupboy** [comment]
Having the AI prefer to found certain religions over others would, as in Civ 5, would be nice

**Comment by xlenstra** [comment]
> The byzantine extra belief still doesn't work. It lets you choose the extra belief but doesn't show up after founding. Also, any plans to split Christianity icons into Catholicism, Eastern Orthodox and Protestantism?

It should hopefully be fixed in the next version, if you can provide a save file before founding your religion and instructions on what you did, I can test that this is indeed the case.
Eventually that will happen, as that was a feature in BNW, but for now we're aiming for G&K so don't count on it soon

**Comment by freddyhayward** [comment]
>  Eventually that will happen, as that was a feature in BNW, but for now we're aiming for G&K so don't count on it soon

Is this strictly a matter of policy? If so, I understand. 
If not, this is a minor change unconnected to G&K mechanics. If it's simply a matter of effort, I could add it myself.

**Comment by MadManMoon** [comment]
Hiya, not asking as a nag, or a poke, but curious if there will be a temple, because it seems to break a few mods.

For example ... Argentina in latin america civs ... The tango wotsit can't be created because there's literally no temples to precede them ... in vanilla or gods/kings.

Again, not a cuss ... just thought I'd ask. Brilliant work, as always!

Will edit in link to raising this as an issue in the latin america civs mod shortly.

**Comment by xlenstra** [comment]
> Hiya, not asking as a nag, or a poke, but curious if there will be a temple, because it seems to break a few mods.
> 
> For example ... Argentina in latin america civs ... The tango wotsit can't be created because there's literally no temples to precede them ... in vanilla or gods/kings.
> 
> Again, not a cuss ... just thought I'd ask. Brilliant work, as always!
> 
> Also raised in the mod, here: https://github.com/ArchDuque-Pancake/Latin-American_Civs/issues/3

Temples have existed in G&K since 3.15.14?

**Comment by MadManMoon** [comment]
Yet there are none in the game. :-(

**Comment by xlenstra** [comment]
> Yet there are none in the game, and it isn't even in the Civlopedia. :-(
> 
> ((( Game is updated in the past two days, beta tester. Tried with a new game, still not listed ... with or without mod started. )))

Which version are you on? On my game they do show up, both in the civilopedia and in-game

**Comment by Kleznam** [comment]
Xlenstra is this issue closed because interdice did the last 34 issue about the religious units ai

**Comment by Kleznam** [comment]
Or is it just an automation

**Comment by MadManMoon** [comment]
I literally updated it the other day to the latest beta, and I can't build temples at all with Argentina (and couldn't before the update) ... and I lost all my saves when I tried to clean it ... also since the cleanse, it can't even run Latin civs or lotr ... ... anyway, ignoring that ... In the civlopedia when you tap on temple links it literally goes nowhere ... hang on a second for the rest because when I use another app/tab Firefox logs me out of everything ...

> Which version are you on? On my game they do show up, both in the civilopedia and in-game (version can be found in settings->about)
> 
> Are you sure you're looking in the right section of the civilopedia? Is it not there both in vanilla & G&K?

**Comment by xlenstra** [comment]
All existing temples should have been replaced with amphitheatres in games without religion since the introduction of those buildings in 3.15.16 (~june 29th). That behaviour only changed with the re-introduction of temples in 3.15.14 (~july 22nd), changing them into faith buildings. If you haven't opened your save between these dates, some funky stuff might have happened, that could corrupt your save files like that. In that case the best advise I can give is to start a new game.

Vanilla has no religion, so it is disabled by default. Other units, buildings, etc. are also removed in vanilla, and therefore some mods (such as Latin American civs) don't work correctly with it. This explains the errors in the first screenshot. The warnings in the second screenshot are caused by the mod not updating to conform to the new uniques that are supported, and as this mod still uses a few old uniques, this gives errors. This results in some abilities of units and buildings not working correctly. This is a problem with the mod, so the mod maker has to changing things, and we cannot.

If you try to open an old save that wasn't yet marked as either G&K or vanilla, it should be automatically turned into a G&K save file, though if any of the mods you have downloaded changed their names, that could break saves, and there is not a lot we can do about that either, as this is fully the responsibility of the mod maker.

**Comment by MadManMoon** [comment]
I totally get that, about the mod/game relationship, mate, cheers. Sorry, hope it's obvious that I'm not leaning on you, here ... because I'm not. :-)

Anyway, yeah ... is there any way for me to alter the save file to point to a new version of the mod? Or would that just be silly amounts of work?

I'll go back to the game and try with a new game save and file ... I'll have to make a map for myself, though, as that map was great. 😅

**Comment by Interdice** [comment]
@Kleznam, the AI I coded is simple. I only intended to code the AI for the Missionary and Inquisitor and did not think that I needed to code the system purchase and decide between Inquisitor and Missionary. 

Anyway my point is the AI I created is rudimentary and can't save faith, or purchase buildings or purchase military units. For the AI to be able to decide on more complex faith spending, we would need to add a "proper" faith construction list.

I tried to connect the faith construction list with the normal construction list but there were technical problems and I ended up scrapping the whole idea, as I just wanted to code the AI for the Missionary and Inquisitor.

**Comment by Interdice** [comment]
@xlenstra The Inquisitor can use its charge. The inquisitor will use its charge to remove religion when all cities are protected

**Comment by whatsupboy** [comment]
According to the original game but also the fact it's really annoying, you should be able to demand that the AI doesnt spread their relegion to your cities. Just like the stop settling demand

**Comment by xlenstra** [comment]
> According to the original game but also the fact it's really annoying, you should be able to demand that the AI doesnt spread their relegion to your cities. Just like the stop settling demand

Part of the diplomacy to-do-list

**Comment by yairm210** [comment]
Oh, cool, didn't know that could happen!

**Comment by PizzaProgram** [comment]
Please add at least 1 word Info (and an icon of that religion) about:
 - What kind of missionaries am I just buying for 200 point.

I've just had to realized:
 - Buying one Inquisitor or Missionary does not necessary have the same religion of my own, but the religion of the (converted) city.

This is not clear at all, because there is not even one word or an icon, that would show:
- What kind of priest am I going to buy if I click the Buy button?

Thanks ;-)
