### ISSUE TITLE
Great Prophets to-do

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4649]
Another reminder for myself:
- [x] double-check GP spawn rate. One every 5 turns in that test game without a sign of slowing down with number of GP spawned doesn't feel right.
- [x] double-check correctness of halicarnassus triggering for "spread" number 4 - is OK
- [ ] look for a holy site tileset sprite??
- [x] check: Is it correct that GP having only a pantheon have the same holy site and spread rights as GP for a full religion?
- [x] Investigate: Empty Strings (as opposed to empty collection) in founderBeliefs, followerBeliefs -> as planned

**Comment by SomeTroglodyte** [comment]
That first one was likely # 4772

**Comment by logicminimal** [comment]
can confirm 2

**Comment by SomeTroglodyte** [comment]
> can confirm 2

I read that as 'I can confirm getting gold for using a G Prophet's last Spread Religion is OK, Civ5 does the same' -> thanks

**Comment by logicminimal** [comment]
> > can confirm 2
> 
> I read that as 'I can confirm getting gold for using a G Prophet's last Spread Religion is OK, Civ5 does the same' -> thanks

yep what i meant
