### ISSUE TITLE
Improve modding documentation checklist

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#4826]
## Improve modding documentation

- [x] [Document _all_ moddable json files](../../Unciv/wiki/JSON-files-for-mods)
- - [x] Terrains.json
- - [x] TileImprovements.json
- - [x] TileResources.json
- - [x] All others
- - [x] FantasyHex.json
- [x] TOC ordering
- [ ] Improve / tighten general json syntax chapter
- [ ] Mention relaxed json standard?
- [x] Split into sub-pages including fixing links
- [x] TOC to Sidebar
- [ ] [Uniques roadmap / what's missing?](../..//wiki/Uniques)
- [ ] Uniques improve structure and TOC
- [x] Check and improve information on game.atlas

Help or input welcome. If you plan on editing a page let's synchronize here. (Hi @xlenstra - thanks for the excellent work)

**Comment by SomeTroglodyte** [comment]
@ravignir  - if I may be so bold - what I wrote for the TileSet jsons [(here)](https://github.com/yairm210/Unciv/wiki/JSON-files-for-mods#tileset-specific-json) isn't complete, Could you please take a look?

**Comment by logicminimal** [comment]
y closed?
